export let Data = [
  {
    Category: 'SSC',
    News: [
      {
        heading: 'SSC design part 0',
        body:
          'SSC Design, a design language for background applications, is refined by Ant UED Team.',
        id: '0',
      },
      {
        heading: 'SSC design part 1',
        body:
          'SSC Design, a design language for background applications, is refined by Ant UED Team.2',
        id: '1',
      },
      {
        heading: 'SSC design part 2',
        body:
          'SSC Design, a design language for background applications, is refined by Ant UED Team.',
        id: '2',
      },
      {
        heading: 'SSC design part 3',
        body:
          'SSC Design, a design language for background applications, is refined by Ant UED Team.',
        id: '3',
      },
      {
        heading: 'SSC design part 4',
        body:
          'SSC Design, a design language for background applications, is refined by Ant UED Team.',
        id: '4',
      },
      {
        heading: 'SSC design part 5',
        body:
          'SSC Design, a design language for background applications, is refined by Ant UED Team.',
        id: '5',
      },
      {
        heading: 'SSC design part 6',
        body:
          'SSC Design, a design language for background applications, is refined by Ant UED Team.',
        id: '6',
      },
      {
        heading: 'SSC design part 7',
        body:
          'Ant Design, a design language for background applications, is refined by Ant UED Team.',
        id: '7',
      },
    ],
    Events: [
      {
        Test_Id: '1',
        Test_Title: 'SSC CGL 2019',
        Rating: '3',
        Number_Of_Questions: '70',
        Category: 'hard',
        Creator: 'vamseewatson',
        Duration: '30 minutes',
        Passing_percentage: '60%',
        Negative_Margin: '0',
        Result_Declaration: 'Immediately after Completion',
        No_Of_Attempt: '1',
        Total_Marks: '100',
        posted: '01/09/2020',
        Descriptions:
          'Following the Ant Design specification, we developed a React UI ',
        Topper: 'Urmilathapa',
      },
      {
        Test_Id: '2',
        Test_Title: 'CISF Constable 2019',
        Rating: '4',
        Number_Of_Questions: '80',
        Category: 'Medium',
        Creator: 'kavin346',
        Duration: '40 minutes',
        Passing_percentage: '30%',
        Negative_Margin: '1.5',
        Result_Declaration: 'Immediately after Completion',
        No_Of_Attempt: '1',
        Total_Marks: '120',
        posted: '01/04/2020',
        Descriptions:
          'Following the Ant Design specification, we developed a React UI ',
        Topper: 'Urmilathapa',
      },
      {
        Test_Id: '3',
        Test_Title: 'Air Force Group X',
        Rating: '2.5',
        Number_Of_Questions: '90',
        Category: 'Easy',
        Creator: 'vighnesh28',
        Duration: '60 minutes',
        Passing_percentage: '33%',
        Negative_Margin: '1',
        Result_Declaration: 'Immediately after Completion',
        No_Of_Attempt: '2',
        Total_Marks: '220',
        posted: '02/02/2020',
        Descriptions:
          'Following the Ant Design specification, we developed a React UI ',
        Topper: 'Urmilathapa',
      },
      {
        Test_Id: '4',
        Test_Title: 'SSC JHT 2019',
        Rating: '5',
        Number_Of_Questions: '100',
        Category: 'Hard',
        Creator: 'ntec75098',
        Duration: '60 minutes',
        Passing_percentage: '66%',
        Negative_Margin: 'none',
        Result_Declaration: 'Immediately after Completion',
        No_Of_Attempt: '1',
        Total_Marks: '150',
        posted: '10/02/2020',
        Descriptions:
          'Following the Ant Design specification, we developed a React UI ',
        Topper: 'Urmilathapa',
      },
      {
        Test_Id: '5',
        Test_Title: 'L&T Info. Test Series',
        Rating: '5',
        Number_Of_Questions: '200',
        Category: 'Hard',
        Creator: 'ntec75098',
        Duration: '120 minutes',
        Passing_percentage: '56%',
        Negative_Margin: 'none',
        Result_Declaration: 'Immediately after Completion',
        No_Of_Attempt: '3',
        Total_Marks: '150',
        posted: '30/02/2020',
        Descriptions:
          'Following the Ant Design specification, we developed a React UI ',
        Topper: 'Urmilathapa',
      },
      {
        Test_Id: '6',
        Test_Title: 'Wipro Test Series',
        Rating: '2',
        Number_Of_Questions: '100',
        Category: 'Hard',
        Creator: 'ntec75098',
        Duration: '80 minutes',
        Passing_percentage: '46%',
        Negative_Margin: 'none',
        Result_Declaration: 'Immediately after Completion',
        No_Of_Attempt: '3',
        Total_Marks: '250',
        posted: '20/02/2020',
        Descriptions:
          'Following the Ant Design specification, we developed a React UI ',
        Topper: 'Urmilathapa',
      },
      {
        Test_Id: '7',
        Test_Title: 'IBPS PO 2019',
        Rating: '4.5',
        Number_Of_Questions: '100',
        Category: 'Hard',
        Creator: 'ntec75098',
        Duration: '80 minutes',
        Passing_percentage: '46%',
        Negative_Margin: 'none',
        Result_Declaration: 'Immediately after Completion',
        No_Of_Attempt: '3',
        Total_Marks: '350',
        posted: '25/02/2020',
        Descriptions:
          'Following the Ant Design specification, we developed a React UI ',
        Topper: 'Urmilathapa',
      },
      {
        Test_Id: '8',
        Test_Title: 'RBI Security Guard',
        Rating: '4',
        Number_Of_Questions: '100',
        Category: 'Hard',
        Creator: 'ntec75098',
        Duration: '80 minutes',
        Passing_percentage: '46%',
        Negative_Margin: 'none',
        Result_Declaration: 'Immediately after Completion',
        No_Of_Attempt: '3',
        Total_Marks: '250',
        posted: '20/02/2020',
        Descriptions:
          'Following the Ant Design specification, we developed a React UI ',
        Topper: 'Urmilathapa',
      },
    ],
    article: [
      {heading: 'HEADING 1', body: 'Article Body 1'},
      {heading: 'HEADING 2', body: 'Article Body 2'},
      {heading: 'HEADING 3', body: 'Article Body 4'},
      {heading: 'HEADING 4', body: 'Article Body 5'},
    ],
    Information: [
      {heading: 'HEADING 1', body: 'Information Body 1'},
      {heading: 'HEADING 2', body: 'Information Body 2'},
      {heading: 'HEADING 3', body: 'Information Body 4'},
      {heading: 'HEASDING 4', body: 'Information Body 5'},
    ],
    ExamInfo: [
      {heading: 'HEADING 1', body: 'ExamInfo Body 1'},
      {heading: 'HEADING 2', body: 'ExamInfo Body 2'},
      {heading: 'HEADING 3', body: 'ExamInfo Body 4'},
      {heading: 'HEADING 4', body: 'ExamInfo Body 5'},
    ],
  },
  {
    Category: 'IIT',
    News: [
      {
        heading: 'IIT design part 0',
        body:
          'IIT Design, a design language for background applications, is refined by Ant UED Team.',
        id: '0',
      },
      {
        heading: 'IIT design part 1',
        body:
          'IIT Design, a design language for background applications, is refined by Ant UED Team.2',
        id: '1',
      },
      {
        heading: 'IIT design part 3',
        body:
          'IIT Design, a design language for background applications, is refined by Ant UED Team.',
        id: '2',
      },
      {
        heading: 'IIT design part 4',
        body:
          'IIT Design, a design language for background applications, is refined by Ant UED Team.',
        id: '3',
      },
    ],
    Events: [
      {
        Test_Id: '1',
        Test_Title: 'SSC CGL 2019',
        Rating: '3',
        Number_Of_Questions: '70',
        Category: 'hard',
        Creator: 'vamseewatson',
        Duration: '30 minutes',
        Passing_percentage: '60%',
        Negative_Margin: '0',
        Result_Declaration: 'Immediately after Completion',
        No_Of_Attempt: '1',
        Total_Marks: '100',
        posted: '01/09/2020',
        Descriptions:
          'Following the Ant Design specification, we developed a React UI ',
        Topper: 'Urmilathapa',
      },
      {
        Test_Id: '2',
        Test_Title: 'CISF Constable 2019',
        Rating: '4',
        Number_Of_Questions: '80',
        Category: 'Medium',
        Creator: 'kavin346',
        Duration: '40 minutes',
        Passing_percentage: '30%',
        Negative_Margin: '1.5',
        Result_Declaration: 'Immediately after Completion',
        No_Of_Attempt: '1',
        Total_Marks: '120',
        posted: '01/04/2020',
        Descriptions:
          'Following the Ant Design specification, we developed a React UI ',
        Topper: 'Urmilathapa',
      },
      {
        Test_Id: '3',
        Test_Title: 'Air Force Group X',
        Rating: '2.5',
        Number_Of_Questions: '90',
        Category: 'Easy',
        Creator: 'vighnesh28',
        Duration: '60 minutes',
        Passing_percentage: '33%',
        Negative_Margin: '1',
        Result_Declaration: 'Immediately after Completion',
        No_Of_Attempt: '2',
        Total_Marks: '220',
        posted: '02/02/2020',
        Descriptions:
          'Following the Ant Design specification, we developed a React UI ',
        Topper: 'Urmilathapa',
      },
      {
        Test_Id: '4',
        Test_Title: 'SSC JHT 2019',
        Rating: '5',
        Number_Of_Questions: '100',
        Category: 'Hard',
        Creator: 'ntec75098',
        Duration: '60 minutes',
        Passing_percentage: '66%',
        Negative_Margin: 'none',
        Result_Declaration: 'Immediately after Completion',
        No_Of_Attempt: '1',
        Total_Marks: '150',
        posted: '10/02/2020',
        Descriptions:
          'Following the Ant Design specification, we developed a React UI ',
        Topper: 'Urmilathapa',
      },
      {
        Test_Id: '5',
        Test_Title: 'L&T Info. Test Series',
        Rating: '5',
        Number_Of_Questions: '200',
        Category: 'Hard',
        Creator: 'ntec75098',
        Duration: '120 minutes',
        Passing_percentage: '56%',
        Negative_Margin: 'none',
        Result_Declaration: 'Immediately after Completion',
        No_Of_Attempt: '3',
        Total_Marks: '150',
        posted: '30/02/2020',
        Descriptions:
          'Following the Ant Design specification, we developed a React UI ',
        Topper: 'Urmilathapa',
      },
      {
        Test_Id: '6',
        Test_Title: 'Wipro Test Series',
        Rating: '2',
        Number_Of_Questions: '100',
        Category: 'Hard',
        Creator: 'ntec75098',
        Duration: '80 minutes',
        Passing_percentage: '46%',
        Negative_Margin: 'none',
        Result_Declaration: 'Immediately after Completion',
        No_Of_Attempt: '3',
        Total_Marks: '250',
        posted: '20/02/2020',
        Descriptions:
          'Following the Ant Design specification, we developed a React UI ',
        Topper: 'Urmilathapa',
      },
      {
        Test_Id: '7',
        Test_Title: 'IBPS PO 2019',
        Rating: '4.5',
        Number_Of_Questions: '100',
        Category: 'Hard',
        Creator: 'ntec75098',
        Duration: '80 minutes',
        Passing_percentage: '46%',
        Negative_Margin: 'none',
        Result_Declaration: 'Immediately after Completion',
        No_Of_Attempt: '3',
        Total_Marks: '350',
        posted: '25/02/2020',
        Descriptions:
          'Following the Ant Design specification, we developed a React UI ',
        Topper: 'Urmilathapa',
      },
      {
        Test_Id: '8',
        Test_Title: 'RBI Security Guard',
        Rating: '4',
        Number_Of_Questions: '100',
        Category: 'Hard',
        Creator: 'ntec75098',
        Duration: '80 minutes',
        Passing_percentage: '46%',
        Negative_Margin: 'none',
        Result_Declaration: 'Immediately after Completion',
        No_Of_Attempt: '3',
        Total_Marks: '250',
        posted: '20/02/2020',
        Descriptions:
          'Following the Ant Design specification, we developed a React UI ',
        Topper: 'Urmilathapa',
      },
    ],
    article: [
      {heading: 'HEADING 1', body: 'Article Body 1'},
      {heading: 'HEADING 2', body: 'Article Body 2'},
      {heading: 'HEADING 3', body: 'Article Body 4'},
      {heading: 'HEADING 4', body: 'Article Body 5'},
    ],
    Information: [
      {heading: 'HEADING 1', body: 'Information Body 1'},
      {heading: 'HEADING 2', body: 'Information Body 2'},
      {heading: 'HEADING 3', body: 'Information Body 4'},
      {heading: 'HEADING 4', body: 'Information Body 5'},
    ],
    ExamInfo: [
      {heading: 'HEADING 1', body: 'ExamInfo Body 1'},
      {heading: 'HEADING 2', body: 'ExamInfo Body 2'},
      {heading: 'HEADING 3', body: 'ExamInfo Body 4'},
      {heading: 'HEADING 4', body: 'ExamInfo Body 5'},
    ],
  },
  {
    Category: 'GATE',
    News: [
      {
        heading: 'GATE design part 0',
        body:
          'GATE Design, a design language for background applications, is refined by Ant UED Team.',
        id: '0',
      },
      {
        heading: 'ant design part 1',
        body:
          'Ant Design, a design language for background applications, is refined by Ant UED Team.2',
        id: '1',
      },
      {
        heading: 'ant design part 3',
        body:
          'Ant Design, a design language for background applications, is refined by Ant UED Team.',
        id: '2',
      },
      {
        heading: 'ant design part 4',
        body:
          'Ant Design, a design language for background applications, is refined by Ant UED Team.',
        id: '3',
      },
    ],
    Events: [
      {
        Test_Id: '1',
        Test_Title: 'SSC CGL 2019',
        Rating: '3',
        Number_Of_Questions: '70',
        Category: 'hard',
        Creator: 'vamseewatson',
        Duration: '30 minutes',
        Passing_percentage: '60%',
        Negative_Margin: '0',
        Result_Declaration: 'Immediately after Completion',
        No_Of_Attempt: '1',
        Total_Marks: '100',
        posted: '01/09/2020',
        Descriptions:
          'Following the Ant Design specification, we developed a React UI ',
        Topper: 'Urmilathapa',
      },
      {
        Test_Id: '2',
        Test_Title: 'CISF Constable 2019',
        Rating: '4',
        Number_Of_Questions: '80',
        Category: 'Medium',
        Creator: 'kavin346',
        Duration: '40 minutes',
        Passing_percentage: '30%',
        Negative_Margin: '1.5',
        Result_Declaration: 'Immediately after Completion',
        No_Of_Attempt: '1',
        Total_Marks: '120',
        posted: '01/04/2020',
        Descriptions:
          'Following the Ant Design specification, we developed a React UI ',
        Topper: 'Urmilathapa',
      },
      {
        Test_Id: '3',
        Test_Title: 'Air Force Group X',
        Rating: '2.5',
        Number_Of_Questions: '90',
        Category: 'Easy',
        Creator: 'vighnesh28',
        Duration: '60 minutes',
        Passing_percentage: '33%',
        Negative_Margin: '1',
        Result_Declaration: 'Immediately after Completion',
        No_Of_Attempt: '2',
        Total_Marks: '220',
        posted: '02/02/2020',
        Descriptions:
          'Following the Ant Design specification, we developed a React UI ',
        Topper: 'Urmilathapa',
      },
      {
        Test_Id: '4',
        Test_Title: 'SSC JHT 2019',
        Rating: '5',
        Number_Of_Questions: '100',
        Category: 'Hard',
        Creator: 'ntec75098',
        Duration: '60 minutes',
        Passing_percentage: '66%',
        Negative_Margin: 'none',
        Result_Declaration: 'Immediately after Completion',
        No_Of_Attempt: '1',
        Total_Marks: '150',
        posted: '10/02/2020',
        Descriptions:
          'Following the Ant Design specification, we developed a React UI ',
        Topper: 'Urmilathapa',
      },
      {
        Test_Id: '5',
        Test_Title: 'L&T Info. Test Series',
        Rating: '5',
        Number_Of_Questions: '200',
        Category: 'Hard',
        Creator: 'ntec75098',
        Duration: '120 minutes',
        Passing_percentage: '56%',
        Negative_Margin: 'none',
        Result_Declaration: 'Immediately after Completion',
        No_Of_Attempt: '3',
        Total_Marks: '150',
        posted: '30/02/2020',
        Descriptions:
          'Following the Ant Design specification, we developed a React UI ',
        Topper: 'Urmilathapa',
      },
      {
        Test_Id: '6',
        Test_Title: 'Wipro Test Series',
        Rating: '2',
        Number_Of_Questions: '100',
        Category: 'Hard',
        Creator: 'ntec75098',
        Duration: '80 minutes',
        Passing_percentage: '46%',
        Negative_Margin: 'none',
        Result_Declaration: 'Immediately after Completion',
        No_Of_Attempt: '3',
        Total_Marks: '250',
        posted: '20/02/2020',
        Descriptions:
          'Following the Ant Design specification, we developed a React UI ',
        Topper: 'Urmilathapa',
      },
      {
        Test_Id: '7',
        Test_Title: 'IBPS PO 2019',
        Rating: '4.5',
        Number_Of_Questions: '100',
        Category: 'Hard',
        Creator: 'ntec75098',
        Duration: '80 minutes',
        Passing_percentage: '46%',
        Negative_Margin: 'none',
        Result_Declaration: 'Immediately after Completion',
        No_Of_Attempt: '3',
        Total_Marks: '350',
        posted: '25/02/2020',
        Descriptions:
          'Following the Ant Design specification, we developed a React UI ',
        Topper: 'Urmilathapa',
      },
      {
        Test_Id: '8',
        Test_Title: 'RBI Security Guard',
        Rating: '4',
        Number_Of_Questions: '100',
        Category: 'Hard',
        Creator: 'ntec75098',
        Duration: '80 minutes',
        Passing_percentage: '46%',
        Negative_Margin: 'none',
        Result_Declaration: 'Immediately after Completion',
        No_Of_Attempt: '3',
        Total_Marks: '250',
        posted: '20/02/2020',
        Descriptions:
          'Following the Ant Design specification, we developed a React UI ',
        Topper: 'Urmilathapa',
      },
    ],
    article: [
      {heading: 'HEADING 1', body: 'Article Body 1'},
      {heading: 'HEADING 2', body: 'Article Body 2'},
      {heading: 'HEADING 3', body: 'Article Body 4'},
      {heading: 'HEADING 4', body: 'Article Body 5'},
    ],
    Information: [
      {heading: 'HEADING 1', body: 'Information Body 1'},
      {heading: 'HEADING 2', body: 'Information Body 2'},
      {heading: 'HEADING 3', body: 'Information Body 4'},
      {heading: 'HEADING 4', body: 'Information Body 5'},
    ],
    ExamInfo: [
      {heading: 'HEADING 1', body: 'ExamInfo Body 1'},
      {heading: 'HEADING 2', body: 'ExamInfo Body 2'},
      {heading: 'HEADING 3', body: 'ExamInfo Body 4'},
      {heading: 'HEADING 4', body: 'ExamInfo Body 5'},
    ],
  },
];
