export const seriesData = [
  {
    Test_Id: "1",
    Test_Name: "SSC CGL 2019",
    Test_Rating: "3",
    Number_Of_Questions: "70",
    Test_Difficulty_Level: "hard",
    Created_By: "vamseewatson",
    Test_Duration: "30 minutes",
    Passing_percentage: "60%",
    Negative_Margin: "0",
    Result_Declaration: "Immediately after Completion",
    No_Of_Attempt: "1",
    Total_Marks: "100",
    Created_Date: "01/09/2020",
    Test_Description:
      "Following the Ant Design specification, we developed a React UI ",
    Topper: "Urmilathapa"
  },
  {
    Test_Id: "2",
    Test_Name: "CISF Constable 2019",
    Test_Rating: "4",
    Number_Of_Questions: "80",
    Test_Difficulty_Level: "Medium",
    Created_By: "kavin346",
    Test_Duration: "40 minutes",
    Passing_percentage: "30%",
    Negative_Margin: "1.5",
    Result_Declaration: "Immediately after Completion",
    No_Of_Attempt: "1",
    Total_Marks: "120",
    posted: "01/04/2020",
    Descriptions:
      "Following the Ant Design specification, we developed a React UI ",
    Topper: "Urmilathapa"
  },
  {
    Test_Id: "3",
    Test_Name: "Air Force Group X",
    Test_Rating: "2.5",
    Number_Of_Questions: "90",
    Test_Difficulty_Level: "Easy",
    Created_By: "vighnesh28",
    Test_Duration: "60 minutes",
    Passing_percentage: "33%",
    Negative_Margin: "1",
    Result_Declaration: "Immediately after Completion",
    No_Of_Attempt: "2",
    Total_Marks: "220",
    posted: "02/02/2020",
    Descriptions:
      "Following the Ant Design specification, we developed a React UI ",
    Topper: "Urmilathapa"
  },
  {
    Test_Id: "4",
    Test_Name: "SSC JHT 2019",
    Test_Rating: "5",
    Number_Of_Questions: "100",
    Test_Difficulty_Level: "Hard",
    Created_By: "ntec75098",
    Duration: "60 minutes",
    Passing_percentage: "66%",
    Negative_Margin: "none",
    Result_Declaration: "Immediately after Completion",
    No_Of_Attempt: "1",
    Total_Marks: "150",
    posted: "10/02/2020",
    Test_Descriptions:
      "Following the Ant Design specification, we developed a React UI ",
    Topper: "Urmilathapa"
  },
  {
    Test_Id: "5",
    Test_Name: "L&T Info. Test Series",
    Test_Rating: "5",
    Number_Of_Questions: "200",
    Test_Difficulty_Level: "Hard",
    Created_by: "ntec75098",
    Test_Duration: "120 minutes",
    Passing_percentage: "56%",
    Negative_Margin: "none",
    Result_Declaration: "Immediately after Completion",
    No_Of_Attempt: "3",
    Total_Marks: "150",
    posted: "30/02/2020",
    Descriptions:
      "Following the Ant Design specification, we developed a React UI ",
    Topper: "Urmilathapa"
  },
  {
    Test_Id: "6",
    Test_Name: "Wipro Test Series",
    Test_Rating: "2",
    Number_Of_Questions: "100",
    Test_Difficulty_Level: "Hard",
    Created_By: "ntec75098",
    Test_Duration: "80 minutes",
    Passing_percentage: "46%",
    Negative_Margin: "none",
    Result_Declaration: "Immediately after Completion",
    No_Of_Attempt: "3",
    Total_Marks: "250",
    posted: "20/02/2020",
    Descriptions:
      "Following the Ant Design specification, we developed a React UI ",
    Topper: "Urmilathapa"
  },
  {
    Test_Id: "7",
    Test_Title: "IBPS PO 2019",
    Rating: "4.5",
    Number_Of_Questions: "100",
    Category: "Hard",
    Creator: "ntec75098",
    Duration: "80 minutes",
    Passing_percentage: "46%",
    Negative_Margin: "none",
    Result_Declaration: "Immediately after Completion",
    No_Of_Attempt: "3",
    Total_Marks: "350",
    posted: "25/02/2020",
    Descriptions:
      "Following the Ant Design specification, we developed a React UI ",
    Topper: "Urmilathapa"
  },
  {
    Test_Id: "8",
    Test_Title: "RBI Security Guard",
    Rating: "4",
    Number_Of_Questions: "100",
    Category: "Hard",
    Creator: "ntec75098",
    Duration: "80 minutes",
    Passing_percentage: "46%",
    Negative_Margin: "none",
    Result_Declaration: "Immediately after Completion",
    No_Of_Attempt: "3",
    Total_Marks: "250",
    posted: "20/02/2020",
    Descriptions:
      "Following the Ant Design specification, we developed a React UI ",
    Topper: "Urmilathapa"
  }
];
