export const GET_QUESTION_LIST = 'GET_QUESTION_LIST';
export const GET_QUESTION_LIST_SUCCESS = 'GET_QUESTION_LIST_SUCCESS';

export const DELETE_QUESTION = 'DELETE_QUESTION';
export const DELETE_QUESTION_SUCCESS = 'DELETE_QUESTION_SUCCESS';

export const ADD_QUESTION = 'ADD_QUESTION';
export const ADD_QUESTION_SUCCESS = 'ADD_QUESTION_SUCCESS';

export const EDIT_QUESTION = 'EDIT_QUESTION';
export const EDIT_QUESTION_SUCCESS = 'EDIT_QUESTION_SUCCESS';

export const IS_GET_QUESTION_LIST_PENDING = 'IS_GET_QUESTION_LIST_PENDING';
export const QUESTION_LOADING_UI = 'QUESTION_LOADING_UI';

export const STOP_QUESTION_LOADING_UI = 'STOP_QUESTION_LOADING_UI';
export const SET_QUESTION_ERROR = 'SET_QUESTION_ERROR';
