//ui related action types
export const SET_BATCH_ERRORS = 'SET_BATCH_ERRORS';
export const BATCH_LOADING_UI = 'BATCH_LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const STOP_BATCH_LOADING_UI = 'STOP_BATCH_LOADING_UI';
//batch related action types
export const GET_BATCH_DETAILS = 'GET_BATCH_DETAILS';
export const GET_BATCH_DETAILS_SUCCESS = 'GET_BATCH_DETAILS_SUCCESS';
export const CREATE_BATCH = 'CREATE_BATCH';
export const CREATE_BATCH_SUCCESS = 'CREATE_BATCH_SUCCESS';
export const UPDATE_BATCH = 'UPDATE_BATCH';
export const UPDATE_BATCH_SUCCESS = 'UPDATE_BATCH_SUCCESS';
export const ACTIVE_BATCH = 'ACTIVE_BATCH';
export const ACTIVE_BATCH_SUCCESS = 'ACTIVE_BATCH_SUCCESS';
export const GET_BATCH_LIST = 'GET_BATCH_LIST';
export const GET_BATCH_LIST_SUCCESS = 'GET_BATCH_LIST_SUCCESS';
export const GET_BATCH_CATEGORY_LIST = 'GET_BATCH_CATEGORY_LIST';
export const GET_BATCH_CATEGORY_LIST_SUCCESS =
  'GET_BATCH_CATEGORY_LIST_SUCCESS';
//student
export const GET_STUDENT_LIST = 'GET_STUDENT_LIST';
export const GET_STUDENT_LIST_SUCCESS = 'GET_STUDENT_LIST_SUCCESS';
export const ADD_STUDENT = 'ADD_STUDENT';
export const ADD_STUDENT_SUCCESS = 'ADD_STUDENT_SUCCESS';
export const DELETE_STUDENT = 'DELETE_STUDENT';
export const DELETE_STUDENT_SUCCESS = 'DELETE_STUDENT_SUCCESS';
export const GET_ALL_STUDENT = 'GET_ALL_STUDENT';
export const GET_ALL_STUDENT_SUCCESS = 'GET_ALL_STUDENT_SUCCESS';
export const ADD_INSTITUTE_STUDENT = 'ADD_INSTITUTE_STUDENT';
export const ADD_INSTITUTE_STUDENT_SUCCESS = 'ADD_INSTITUTE_STUDENT_SUCCESS';
//teacher
export const GET_TEACHER_LIST = 'GET_TEACHER_LIST';
export const GET_TEACHER_LIST_SUCCESS = 'GET_TEACHER_LIST_SUCCESS';
export const DELETE_TEACHER_SUCCESS = 'DELETE_TEACHER_SUCCESS';
export const DELETE_TEACHER = 'DELETE_TEACHER';
export const ADD_INSTITUTE_TEACHER = 'ADD_INSTITUTE_TEACHER';
export const ADD_INSTITUTE_TEACHER_SUCCESS = 'ADD_INSTITUTE_TEACHER_SUCCESS';
export const GET_INSTITUTE_TEACHER = 'GET_INSTITUTE_TEACHER';
export const GET_INSTITUTE_TEACHER_SUCCESS = 'GET_INSTITUTE_TEACHER_SUCCESS';
//subject
export const GET_SUBJECT_LIST = 'GET_SUBJECT_LIST';
export const GET_SUBJECT_LIST_SUCCESS = 'GET_SUBJECT_LIST_SUCCESS';
export const ADD_SUBJECT = 'ADD_SUBJECT';
export const ADD_SUBJECT_SUCCESS = 'ADD_SUBJECT_SUCCESS';
export const DELETE_SUBJECT = 'DELETE_SUBJECT';
export const DELETE_SUBJECT_SUCCESS = 'DELETE_SUBJECT_SUCCESS';
export const DELETE_SUBJECT_FACULTY = 'DELETE_SUBJECT_FACULTY';
export const DELETE_SUBJECT_FACULTY_SUCCESS = 'DELETE_SUBJECT_FACULTY_SUCCESS';

//announcement
export const CREATE_ANNOUNCEMENT = 'CREATE_ANNOUNCEMENT';
export const CREATE_ANNOUNCEMENT_SUCCESS = 'CREATE_ANNOUNCEMENT_SUCCESS';
export const UPDATE_ANNOUNCEMENT = 'UPDATE_ANNOUNCEMENT';
export const UPDATE_ANNOUNCEMENT_SUCCESS = 'UPDATE_ANNOUNCEMENT_SUCCESS';
export const GET_ANNOUNCEMENT_LIST = 'GET_ANNOUNCEMENT_LIST';
export const GET_ANNOUNCEMENT_LIST_SUCCESS = 'GET_ANNOUNCEMENT_LIST_SUCCESS';
export const DELETE_ANNOUNCEMENT = 'DELETE_ANNOUNCEMENT';
export const DELETE_ANNOUNCEMENT_SUCCESS = 'DELETE_ANNOUNCEMENT_SUCCESS';
// export const SEND_ANNOUNCEMENT = 'SEND_ANNOUNCEMENT';
// export const SEND_ANNOUNCEMENT_SUCCESS = 'SEND_ANNOUNCEMENT_SUCCESS';
//assignment
export const CREATE_ASSIGNMENT = 'CREATE_ASSIGNMENT';
export const CREATE_ASSIGNMENT_SUCCESS = 'CREATE_ASSIGNMENT_SUCCESS';
export const UPDATE_ASSIGNMENT = 'UPDATE_ASSIGNMENT';
export const UPDATE_ASSIGNMENT_SUCCESS = 'UPDATE_ASSIGNMENT_SUCCESS';
export const GET_ASSIGNMENT_LIST = 'GET_ASSIGNMENT_LIST';
export const GET_ASSIGNMENT_LIST_SUCCESS = 'GET_ASSIGNMENT_LIST_SUCCESS';
export const DELETE_ASSIGNMENT = 'DELETE_ASSIGNMENT';
export const DELETE_ASSIGNMENT_SUCCESS = 'DELETE_ASSIGNMENT_SUCCESS';
