export const ADD_TEST = 'ADD_TEST';
export const ADD_SUCCESS = 'ADD_SUCCESS';

export const DELETE_TEST = 'DELETE_TEST';
export const DELETE_SUCCESS = 'DELETE_SUCCESS';

export const EDIT_TEST = 'EDIT_TEST';
export const EDIT_SUCCESS = 'EDIT_SUCCESS';

export const GET_TEST_LIST = 'GET_TEST_LIST';
export const GET_TEST_LIST_SUCCESS = 'GET_TEST_LIST_SUCCESS';

export const PUBLISH_TEST = 'PUBLISH_TEST';
export const PUBLISH_TEST_SUCCESS = 'PUBLISH_TEST_SUCCESS';

export const TEST_LOADING_UI = 'TEST_LOADING_UI';
export const STOP_TEST_LOADING_UI = 'STOP_TEST_LOADING_UI';
export const SET_TEST_ERROR = 'SET_TEST_ERROR';

export const GET_TEST_ANALYTICS = 'GET_TEST_ANALYTICS';
export const GET_TEST_ANALYTICS_SUCCESS = 'GET_TEST_ANALYTICS_SUCCESS';

export const GET_ATTEMPT_LIST = 'GET_ATTEMPT_LIST';
export const GET_ATTEMPT_LIST_SUCCESS = 'GET_ATTEMPT_LIST_SUCCESS';
