export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const LOGIN_USER_WITH_GOOGLE = 'LOGIN_USER_WITH_GOOGLE';
export const LOGIN_USER_WITH_GOOGLE_SUCCESS = 'LOGIN_USER_WITH_GOOGLE_SUCCESS';
export const LOGIN_USER_WITH_GOOGLE_ERROR = 'LOGIN_USER_WITH_GOOGLE_ERROR';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_ERROR = 'LOGOUT_USER_ERROR';
